services:
  db:
    image: postgres
    restart: unless-stopped
    shm_size: 128mb
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: "${DATABASE_USER:-admin}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD:?Please configure DATABASE_PASSWORD in the .env file}"
      POSTGRES_DB: "voyarch"

  adminer:
    image: "adminer"
    restart: "unless-stopped"
    ports:
      - 8080:8080
